version: "3.9"
services:
  gondola_web:
    build: .
    entrypoint:
      - npm
      - start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t      
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app    
    